In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("diabetes.csv")

In [3]:
df.head(1)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1

In [5]:
correlation_with_outcome = df.corr()["Outcome"]
print(correlation_with_outcome)


Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64


In [6]:
X = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values

In [7]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
Y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [24]:
X = scaler.fit_transform(X)

In [25]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [31]:
X.shape

(768, 8)

In [51]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test , = train_test_split(X,Y,test_size = 0.2 ,random_state = 1)

In [52]:
import tensorflow 
from tensorflow import keras 
from keras import Sequential
from keras.layers import Dense

In [53]:
# model = Sequential()

# model.add(Dense(32, activation = "relu ", input_dim = 8))
# model.add (Dense(1,activation = "sigmoid "))

# Create a Sequential model
model = Sequential()

# Add layers to the model
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation='sigmoid'))

C:\Users\furqi\AppData\Local\anaconda3\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [54]:
model.compile(optimizer= "Adam",loss = "binary_crossentropy", metrics =["accuracy"])

In [57]:
model.fit(X_train,Y_train ,batch_size = 32 ,epochs= 100
          , validation_data = (X_test,Y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7730 - loss: 0.4502 - val_accuracy: 0.7662 - val_loss: 0.4706
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7719 - loss: 0.4533 - val_accuracy: 0.7662 - val_loss: 0.4686
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7774 - loss: 0.4470 - val_accuracy: 0.7662 - val_loss: 0.4694
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7836 - loss: 0.4520 - val_accuracy: 0.7662 - val_loss: 0.4696
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7784 - loss: 0.4584 - val_accuracy: 0.7662 - val_loss: 0.4705
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8134 - loss: 0.4139 - val_accuracy: 0.7662 - val_loss: 0.4711
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7691 - loss: 0.4573 - val_accuracy: 0.7662 - val_loss: 0.4730
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4603 - val_accuracy: 0.7662 - v

20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7952 - loss: 0.4272 - val_accuracy: 0.7922 - val_loss: 0.4670
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8116 - loss: 0.4187 - val_accuracy: 0.7922 - val_loss: 0.4683
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4192 - val_accuracy: 0.7922 - val_loss: 0.4678
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7751 - loss: 0.4518 - val_accuracy: 0.7922 - val_loss: 0.4671
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8065 - loss: 0.4323 - val_accuracy: 0.7857 - val_loss: 0.4683
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8218 - loss: 0.3871 - val_accuracy: 0.7857 - val_loss: 0.4684
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7796 - loss: 0.4605 - val_accuracy: 0.7857 - val_loss: 0.4666
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8499 - loss: 0.3761 - val_accuracy: 0.7857 - val_lo

In [61]:
'''''''how to select apporate optimizer''''' 2 : 
number of node in a layer
how to selesct number of layers 
all in one model'''''''''''

"how to select apporate optimizer' 2 : \nnumber of node in a layer\nhow to selesct number of layers \nall in one model"

In [63]:
# import kerastuner as kt


In [64]:
pip install keras-tuner


     ------------------------------------ 129.1/129.1 kB 281.8 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [65]:
import keras_tuner as kt


In [67]:
import keras_tuner as kt
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

# Define the number of features in your dataset
input_dim = 8  # Replace this with the actual number of features

# Define the model-building function
def build_model(hp):
    model = Sequential()
    
    # Tuning the number of units in the hidden layer
    model.add(layers.Dense(units=hp.Int('units', min_value=32, max_value=128, step=32),
                           activation='relu',
                           input_shape=(input_dim,)))  # Use the defined number of features
    
    model.add(layers.Dense(1, activation='sigmoid'))
    
    # Tuning the optimizer
    model.compile(optimizer=hp.Choice('optimizer', values=['adam', 'rmsprop']),
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    ret


In [68]:
import keras_tuner
import keras

In [69]:
def build_model(hp):
  model = keras.Sequential()
  model.add(keras.layers.Dense(
      hp.Choice('units', [8, 16, 32]),
      activation='relu'))
  model.add(keras.layers.Dense(1, activation='relu'))
  model.compile(loss='mse')
  return model

In [70]:
tuner = keras_tuner.RandomSearch(
    build_model,
    objective='val_loss',
    max_trials=5)

In [72]:
tuner.search(X_train, Y_train, epochs=5)
best_model = tuner.get_best_models()[0]

Trial 2 Complete [00h 00m 02s]

Best val_loss So Far: None
Total elapsed time: 00h 00m 06s

Search: Running Trial #3

Value             |Best Value So Far |Hyperparameter
8                 |16                |units

Epoch 1/5
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3884   
Epoch 2/5
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3706 
Epoch 3/5
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3311 
Epoch 4/5
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2937 
Epoch 5/5
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2914 


Traceback (most recent call last):
  File "C:\Users\furqi\AppData\Local\anaconda3\lib\site-packages\keras_tuner\src\engine\base_tuner.py", line 274, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "C:\Users\furqi\AppData\Local\anaconda3\lib\site-packages\keras_tuner\src\engine\base_tuner.py", line 265, in _run_and_update_trial
    tuner_utils.convert_to_metrics_dict(
  File "C:\Users\furqi\AppData\Local\anaconda3\lib\site-packages\keras_tuner\src\engine\tuner_utils.py", line 132, in convert_to_metrics_dict
    [convert_to_metrics_dict(elem, objective) for elem in results]
  File "C:\Users\furqi\AppData\Local\anaconda3\lib\site-packages\keras_tuner\src\engine\tuner_utils.py", line 132, in <listcomp>
    [convert_to_metrics_dict(elem, objective) for elem in results]
  File "C:\Users\furqi\AppData\Local\anaconda3\lib\site-packages\keras_tuner\src\engine\tuner_utils.py", line 145, in convert_to_metrics_dict
    best_value, _ = _get_best_va

RuntimeError: Number of consecutive failures exceeded the limit of 3.
Traceback (most recent call last):
  File "C:\Users\furqi\AppData\Local\anaconda3\lib\site-packages\keras_tuner\src\engine\base_tuner.py", line 274, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "C:\Users\furqi\AppData\Local\anaconda3\lib\site-packages\keras_tuner\src\engine\base_tuner.py", line 265, in _run_and_update_trial
    tuner_utils.convert_to_metrics_dict(
  File "C:\Users\furqi\AppData\Local\anaconda3\lib\site-packages\keras_tuner\src\engine\tuner_utils.py", line 132, in convert_to_metrics_dict
    [convert_to_metrics_dict(elem, objective) for elem in results]
  File "C:\Users\furqi\AppData\Local\anaconda3\lib\site-packages\keras_tuner\src\engine\tuner_utils.py", line 132, in <listcomp>
    [convert_to_metrics_dict(elem, objective) for elem in results]
  File "C:\Users\furqi\AppData\Local\anaconda3\lib\site-packages\keras_tuner\src\engine\tuner_utils.py", line 145, in convert_to_metrics_dict
    best_value, _ = _get_best_value_and_best_epoch_from_history(
  File "C:\Users\furqi\AppData\Local\anaconda3\lib\site-packages\keras_tuner\src\engine\tuner_utils.py", line 116, in _get_best_value_and_best_epoch_from_history
    objective_value = objective.get_value(metrics)
  File "C:\Users\furqi\AppData\Local\anaconda3\lib\site-packages\keras_tuner\src\engine\objective.py", line 59, in get_value
    return logs[self.name]
KeyError: 'val_loss'
